### PR TITLE
Fix RTD configuration

### PR DESCRIPTION
**Pull request by amotl**
This is a followup patch to GH-142, incorporating some learnings from GH-139, and from https://github.com/coddingtonbear/python-measurement/pull/77. Thank you, @codingjoe.

Other than some refactorings, the patch hopefully fixes the RTD build, by installing the `libeccodes-dev` and `libgeos-dev` distribution packages, in order to satisfy the installation of `cartopy` and friends.

### CODE REVIEW

**Comment by amotl** [comment]
I've just submitted a support request to RTD.

---

Dear lovely Read the Docs team,

first things first, I wish you an excellent new year.

We are in the progress of adding the documentation of Herbie [1] to Read the Docs, but, after believing we got everything in place with [2], we are running into timeouts on the build process, like outlined at [3].

We can't make any sense of that, so we are humbly asking if you have any suggestions for us?

With kind regards,
Andreas.

[1] https://github.com/blaylockbk/Herbie
[2] https://github.com/blaylockbk/Herbie/pull/145
[3] https://readthedocs.org/projects/herbie/builds/19126011/

**Comment by blaylockbk** [comment]
Thanks for asking rtd support. Another dependency Herbie has that can't be installed with pure pip is cfgrib, which requires eccodes.

**Comment by blaylockbk** [comment]
This might help us...looks like rtd lets us specify a conda environment.
https://docs.readthedocs.io/en/stable/config-file/v2.html#conda

**Comment by amotl** [comment]
Hi Brian,

while I admit Conda is absolutely needed to keep ones sanity in non-Linux environments, at GH-139, I've deliberately chosen to not use Conda for the Linux tests, in order to save cycles. Those jobs will happen to run so often that I believe it really makes a difference not wasting resources.

With those dependencies, Herbie would install and run its test suite without issues.

https://github.com/blaylockbk/Herbie/blob/899fb5fb7305019da8786eed23acbcbc82c31016/.github/workflows/tests-python.yml#L57-L60

With kind regards,
Andreas.

P.S.: I admit I did not go into the details of installing `wgrib2` yet. But I am sure there will be a way to install it "natively" on Linux, without needing to use Conda?

**Comment by amotl** [comment]
Hi again. 3ffd4f79 may have improved the situation. [1] shows a successful build, and the documentation can be inspected at [2].

[1] https://readthedocs.org/projects/herbie/builds/19130539/
[2] https://herbie--145.org.readthedocs.build/en/145/

**Review by blaylockbk — APPROVED** [review]

**Comment by blaylockbk** [comment]
Wonderful! It's good to see the docs again. It sure was nice that I didn't have to build the docs myself. Thank you for tracking down the unexpected issues and figuring out how to address them. This really helps Herbie feel more "grown up".

Now I'll take a look at the other tasks you brought up 👍🏻

again, thank you!

**Pull request merged**
