### PR TITLE
update GFS and GEFS template

### LINKED ISSUE #333: Add 13km GFS product
GFS model produced a highres fields on 1536*3072 grid (about 0.117 degree / 13 km)
For example
https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20240625/00/atmos/gfs.t00z.sfluxgrbf024.grib2.idx

### PR DESCRIPTION
**Pull request by blaylockbk**
- Added if block for datetime to switch to GFS v16 file structure.
- Added sfluxgrb product discovery (fixes #333)
- Fixed bug in gdas from azure
- Updated the GEFS template to access earlier data.  
- added ncar_rda as source for GFS, except this source can only download full GFS files. 

Question.
- What is the difference between `anl` files and `f000` files?

### CODE REVIEW

**Review by blaylockbk — COMMENTED** [review]
Still would like to include access to NCEI for GFS before 2021. Need to investigate the NCEI file structure to see if it is at all like what is currently avaialble.

**Comment by vwgeiser** [comment]
They had an option to ask a question about the RDA dataset through UCAR service desk. I inquired about the index files, I can leave updates here when I get them.

I noticed on line 29 there is the code `self.date < datetime(2021, 3, 23)` is this the correct implementation for a date check in Herbie? Could this be used in my current attempt at solving a similar date check problem in #355 ?

**Comment by blaylockbk** [comment]
Thanks @vwgeiser for your code comment in #355. It was very useful. I used that in [e47ecba](https://github.com/blaylockbk/Herbie/pull/358/commits/e47ecbadb57a826c786201ab5e4ccdae5cca66ba). There was a slight change in the way the lead time was expressed in the file name between dates (`f##` versus `f###`). 

I only tested this a little, but it seems to work. 

FYI: I appreciate your error catching in your code for if a user supplied a bad date, but for Herbie I prefer not raising an error here. Herbie returns `None` for `H.grib` when it didn't find a file in any of the URLs, and I leave it up to the user to handle that case and investigate why none of the URLs in `H.SOURCES` are not valid. My reasoning is that the range of dates the different cloud platforms provide data for change over time.

**Comment by vwgeiser** [comment]
@blaylockbk Gotcha, makes sense about the returning `None` vs throwing an error. I appreciate the mention, I'll be testing this today with my workflow and I'll let you know if anything else pops up.

**Comment by vwgeiser** [comment]
@blaylockbk These changes look good. I updated my local Herbie installation and it works in addressing some of the issues in #325 and #355. Bummer about the no index files for ncar_rda, I'll let you know if I can think of any other work around.

**Review by vwgeiser — APPROVED** [review]
Changes look good. Addresses issues in #325 and #355.

**Pull request merged**
